version: 2
jobs:
  build:
    docker:
      - image: j5api/ci:latest
    steps:
      - checkout
      - run: pipenv sync --dev
      - run: pipenv run lint
      - run: pipenv run type
      - run: cc-test-reporter before-build
      - run: pipenv run test-ci
      - run: cc-test-reporter after-build -t coverage.py --exit-code $? coverage.xml
